/************************************************************************

    fx3-bootimage.h

    FX3 boot image construction for the Domesday Duplicator
    DomesdayDuplicator - LaserDisc RF sampler
    Copyright (C) 2026 Simon Inns

    This file is part of Domesday Duplicator.

    Domesday Duplicator is free software: you can redistribute it and/or
    modify it under the terms of the GNU General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

    Email: simon.inns@gmail.com

************************************************************************/

/*
 * The pure half of fx3-mkimage: ELF32 parsing and boot image construction,
 * both operating on memory buffers so they can be tested without touching a
 * filesystem. All file I/O lives in main.c.
 *
 * The boot image format is specified in Infineon application note AN76405,
 * "EZ-USB FX3/FX3S boot options", section 4.4 ("Boot image format") and its
 * worked example in 4.4.1. That note is public and needs no login. See
 * ../README.md for the format summary and for the two behaviours that are
 * *not* in the specification.
 */

#ifndef FX3_BOOTIMAGE_H
#define FX3_BOOTIMAGE_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Image header constants, AN76405 Table 14. */
#define FX3_SIGNATURE_0 0x43u /* 'C' */
#define FX3_SIGNATURE_1 0x59u /* 'Y' */

/* bImageType = 0xB0: normal firmware binary image with checksum. */
#define FX3_IMAGE_TYPE_NORMAL 0xB0u

/*
 * bImageCTL. Bit 0 clear selects an executable image (the bootloader jumps to
 * the program entry); bits 3:1 and 5:4 carry the EEPROM size and bus speed and
 * are ignored unless the device actually boots from I2C or SPI.
 *
 * 0x1C is the value the vendor's own tool emits, and AN76405 confirms it as
 * "the default value of bImageCTL byte in .img files generated by the FX3 SDK"
 * (64 KB EEPROM, 400 kHz I2C / 20 MHz SPI). Keeping the same default is what
 * makes this tool a drop-in replacement.
 */
#define FX3_IMAGE_CTL_DEFAULT 0x1Cu

/*
 * The ARM926EJ-S keeps its reset and interrupt vectors in the first 256 bytes
 * of the address map. Firmware copies them there itself once running, so
 * anything the link placed in that range is dropped from the image by default
 * rather than being loaded over the live bootloader.
 */
#define FX3_VECTOR_AREA_END 0x100u

/*
 * Maximum bytes per image section. This is NOT a requirement of AN76405, which
 * places no limit on a section's length -- it is what the vendor tool does, and
 * matching it is what makes the output byte-identical. See ../README.md.
 */
#define FX3_MAX_SECTION_BYTES 0x10000u

/* Sanity bound on the ELF program header count, so a corrupt file cannot make
 * the caller allocate an unreasonable array. */
#define FX3_MAX_SEGMENTS 64u

/*
 * One loadable region. `data` borrows from the caller's ELF buffer and holds
 * `file_size` bytes; the image places `mem_size` bytes, zero-filling the
 * difference. That difference is .bss, and pre-zeroing it in the image is what
 * the vendor tool does -- see ../README.md.
 */
typedef struct {
    uint32_t address;
    const uint8_t *data;
    size_t file_size;
    size_t mem_size;
} fx3_segment;

typedef enum {
    FX3_OK = 0,
    FX3_E_TRUNCATED,
    FX3_E_NOT_ELF,
    FX3_E_NOT_ELF32_LSB,
    FX3_E_NOT_ARM,
    FX3_E_NOT_EXEC,
    FX3_E_TOO_MANY_SEGMENTS,
    FX3_E_NO_SEGMENTS,
    FX3_E_NOMEM
} fx3_status;

/* Human-readable form of a status code. Never returns NULL. */
const char *fx3_strerror(fx3_status status);

/*
 * Parse an ELF32 little-endian ARM executable held entirely in memory.
 *
 * Fills `segs` with the PT_LOAD segments that have a non-zero memory size, in
 * program-header order, and writes the entry point to `entry`. Every read is
 * bounds-checked against `elf_size`.
 *
 * Returns FX3_E_TOO_MANY_SEGMENTS if the file declares more loadable segments
 * than `max_segs`.
 */
fx3_status fx3_elf_parse(const uint8_t *elf, size_t elf_size, fx3_segment *segs, size_t max_segs,
                         size_t *n_segs, uint32_t *entry);

/*
 * Build a boot image from parsed segments.
 *
 * On success `*out` is a malloc'd buffer of `*out_size` bytes that the caller
 * must free. `keep_vectors` non-zero retains data in the 0x00-0x100 vector
 * area rather than dropping it.
 *
 * Segments are emitted in the order given, split at FX3_MAX_SECTION_BYTES, and
 * padded up to a 4-byte boundary -- the format counts sections in 32-bit words,
 * so a section length is always a whole number of words.
 */
fx3_status fx3_build_image(const fx3_segment *segs, size_t n_segs, uint32_t entry,
                           uint8_t image_ctl, uint8_t image_type, int keep_vectors, uint8_t **out,
                           size_t *out_size);

#ifdef __cplusplus
}
#endif

#endif /* FX3_BOOTIMAGE_H */
