/************************************************************************

	version.vh
	Gateware version stamp

	Domesday Duplicator - LaserDisc RF sampler
	SPDX-FileCopyrightText: 2026 Simon Inns
	SPDX-License-Identifier: GPL-3.0-or-later

	Generated by fpga/generate-version.sh - do not edit.

	Commit: unknown

************************************************************************/

`ifndef GATEWARE_VERSION_VH
`define GATEWARE_VERSION_VH

`define GATEWARE_COMMIT_TEXT 64'h0000000000000000
`define GATEWARE_BUILD_FLAGS 8'h00

`endif
