nav:
  - index.md
  - Linux (Flatpak): install-flatpak.md
  - macOS (DMG): install-dmg.md
  - Windows (MSI): install-msi.md
  - Capture formats: capture-formats.md
  - Updating your Domesday Duplicator: updating-your-domesday-duplicator.md
  - Building from source: building-from-source.md
  - User Guide for Linux: user-guide.md
