#!/usr/bin/env bash
#
# Format the hand-written gateware.
#
# Domesday Duplicator - LaserDisc RF sampler
# SPDX-FileCopyrightText: 2026 Simon Inns
# SPDX-License-Identifier: GPL-3.0-or-later
#
#   nix develop .#fpga -c fpga/tests/run-format.sh
#
# This is the fixer for the formatting half of run-style.sh: it rewrites the
# project-authored sources in place to be exactly what ../.verible-format says.
# There are no options, because a formatter with options is a formatter people
# argue with.
#
# It is deliberately not a Nix check. A check that edits the tree is not a check,
# and CI must report the difference rather than paper over it — see run-style.sh.
#
# It does not touch comment interiors, which no formatter should. Tabs and column
# alignment inside a comment block are a matter for the author and for review.

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fpga="$(dirname "$here")"
src="${1:-$fpga/src}"
tests="${2:-$fpga/tests}"

format_flags="$fpga/.verible-format"

# Kept identical to the list in run-style.sh, and named rather than globbed for the
# reasons given there: the MegaWizard IP must not be reformatted, and version.vh is
# generated by generate-version.sh.
files=(
    "$src/DomesdayDuplicator.v"
    "$src/buffer.v"
    "$src/dataGenerator.v"
    "$src/fifo.v"
    "$src/fx3StateMachine.v"
    "$src/spiRegisters.v"
    "$tests/tb_buffer.v"
    "$tests/tb_dataGenerator.v"
    "$tests/tb_fifo.v"
    "$tests/tb_fx3StateMachine.v"
    "$tests/tb_spiRegisters.v"
)

changed=0

for file in "${files[@]}"; do
    printf '%-24s ' "$(basename "$file")"

    if verible-verilog-format --flagfile="$format_flags" --verify "$file" >/dev/null 2>&1; then
        echo "unchanged"
        continue
    fi

    verible-verilog-format --flagfile="$format_flags" --inplace "$file"
    echo "formatted"
    changed=$((changed + 1))
done

echo
if [ "$changed" -eq 0 ]; then
    echo "Already formatted; nothing to do."
else
    echo "$changed of ${#files[@]} files reformatted."
    echo
    echo "Formatting cannot change behaviour, but say so with evidence rather than by"
    echo "assertion: ./fpga/tests/run-lint.sh and ./fpga/tests/run-sim.sh must both"
    echo "still pass, and a rebuilt DomesdayDuplicator.jic should be byte-identical to"
    echo "the one built before the change (fpga/README.md, \"Reproducibility\")."
fi
