/************************************************************************

    stock_tar_bundle.h

    A bundle as GNU tar and minisign actually produced it
    Domesday Duplicator - LaserDisc RF sampler
    SPDX-FileCopyrightText: 2026 Simon Inns
    SPDX-License-Identifier: GPL-3.0-or-later

************************************************************************/

#pragma once

#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

// The golden bundle: the exact bytes tools/make-update-bundle.sh produced,
// running GNU tar 1.35 and minisign 0.12 over the payloads and manifest in
// update_fixtures.h.
//
// Everything else in the update tests reads archives this project's own writer
// produced, which proves the reader and the writer agree with each other and
// nothing more. The released artefact is made by stock tar, and this is the one
// fixture that says the reader reads *that*. Without it, a difference between
// the two — a magic string, a numeric field's terminator, the padding at the
// end — would not show up until a user downloaded a release and the application
// told them it was corrupt.
//
// Regenerating it, if the manifest fixture ever changes:
//
//   ./tools/make-update-bundle.sh --output
//   domesday-duplicator-update-1.4.0.dddfw
//       --version 1.4.0 --commit 0123abcd --channel development
//       --secret-key tools/keys/development.key
//       --created 2026-08-14T09:15:00Z --notes "<the release notes line>"
//       --firmware firmware.img --firmware-identity 0123abcd
//       --gateware gateware-app.rpd --gateware-identity 0123abcd
//       --gateware-interface-version 2 --minimum-register-map-version 2
//
// then base64 the file's content blocks. GNU tar pads its output to a
// 10,240-byte record by default and only the first 4,608 bytes of this one are
// anything but zeros, so the padding is not stored here — the test appends it,
// and checks both the minimum two-block ending and the full record the real
// file carries.

namespace ddd::capture::test {

// The archive's content blocks, base64 encoded.
//
// clang-format is turned off across it because the formatter would reflow the
// literal into whatever fits its column limit, which would make every future
// regeneration of this fixture a whole-block diff rather than a change to the
// lines that differ.
// clang-format off
inline constexpr std::string_view kStockTarBundleBase64 =
    "bWFuaWZlc3QuanNvbgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAw"
    "MDA2NDQAMDAwMDAwMAAwMDAwMDAwADAwMDAwMDAxNDUwADAwMDAwMDAwMDAwADAxMDQ0"
    "NgAgMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAB1c3RhcgAwMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAB7CiAgIm1hbmlmZXN0X3ZlcnNpb24iOiAxLAogICJjaGFubmVsIjogImRldmVsb3Bt"
    "ZW50IiwKICAidmVyc2lvbiI6ICIxLjQuMCIsCiAgImNvbW1pdCI6ICIwMTIzYWJjZCIs"
    "CiAgImNyZWF0ZWQiOiAiMjAyNi0wOC0xNFQwOToxNTowMFoiLAogICJyZWxlYXNlX25v"
    "dGVzIjogIlRlc3QgYnVuZGxlIGZvciB0aGUgdXBkYXRlIHRvb2xpbmcgdW5pdCB0ZXN0"
    "cy4iLAogICJjb21wb25lbnRzIjogewogICAgImZpcm13YXJlIjogewogICAgICAiZmls"
    "ZSI6ICJmaXJtd2FyZS5pbWciLAogICAgICAibGVuZ3RoIjogNDIsCiAgICAgICJzaGEy"
    "NTYiOiAiYzg0MjJmODE3YjY5ZmE2ODc1MzFiMjZmNGYxOTBiMmM0YTk3ZmU3YjY3OTE4"
    "NTBmZjc2ZGMxMGEyZDUyYjJkOSIsCiAgICAgICJpZGVudGl0eSI6ICIwMTIzYWJjZCIs"
    "CiAgICAgICJpbnRlcmZhY2VfdmVyc2lvbiI6IDEKICAgIH0sCiAgICAiZ2F0ZXdhcmUi"
    "OiB7CiAgICAgICJmaWxlIjogImdhdGV3YXJlLWFwcC5ycGQiLAogICAgICAibGVuZ3Ro"
    "IjogNTUsCiAgICAgICJzaGEyNTYiOiAiNzNhZjEyYzQwY2I5ZjAyYzAzZDg0MTYyMjE3"
    "YTg0MTU0NGZiNWNiN2QyZGRhOWZkZDAwZmZmOGU5ZDExN2MyYSIsCiAgICAgICJpZGVu"
    "dGl0eSI6ICIwMTIzYWJjZCIsCiAgICAgICJpbnRlcmZhY2VfdmVyc2lvbiI6IDIKICAg"
    "IH0KICB9LAogICJjb21wYXRpYmlsaXR5IjogewogICAgIm1pbmltdW1fYXBwbGljYXRp"
    "b25fdmVyc2lvbiI6ICIxLjQuMCIsCiAgICAibWluaW11bV9yZWdpc3Rlcl9tYXBfdmVy"
    "c2lvbiI6IDIsCiAgICAiZXBjc19sYXlvdXRfdmVyc2lvbiI6IDEKICB9Cn0KAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAbWFuaWZlc3QubWluaXNpZwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAADAwMDA2NDQAMDAwMDAwMAAwMDAwMDAwADAwMDAwMDAwNTIzADAwMDAwMDAwMDAw"
    "ADAxMTEzNAAgMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAB1c3RhcgAwMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAB1bnRydXN0ZWQgY29tbWVudDogRG9tZXNkYXkgRHVwbGljYXRvciB1cGRh"
    "dGUgYnVuZGxlIDEuNC4wClJVUjgyQXk4SVFQbmlWVlNjZnBwajVjRVhsUVpQSmtCSDc1"
    "cFBjamdxN2dQTTRQOTMyM0lVZXRnMFYyRVltcW05dzdaYlhSTTVFdStZSU41ZExpanBP"
    "Q2IyRFp3Y2hlcEpndz0KdHJ1c3RlZCBjb21tZW50OiBkb21lc2RheS1kdXBsaWNhdG9y"
    "LXVwZGF0ZS0xLjQuMC5kZGRmdyB2ZXJzaW9uIDEuNC4wIGNoYW5uZWwgZGV2ZWxvcG1l"
    "bnQKUEJaVjV4a0RJVEpYOTdFeWx3cXRlZFQrejNYdStGRkp0WEpYcTFkREFLZ0NZTG52"
    "L2dnZG9kdlVXeUNlOHJjQUZ5UHl2R1VBZVBlNzM3RytkUS9KQmc9PQoAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAGZpcm13YXJlLmltZwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAwMDAwNjQ0ADAwMDAwMDAAMDAwMDAwMAAwMDAwMDAwMDA1MgAwMDAwMDAw"
    "MDAwMAAwMTAyNTQAIDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAdXN0YXIAMDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAARlgzIGZpcm13YXJlIHBheWxvYWQsIGZvciB0aGUgdGVzdHMgb25s"
    "eS4KAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAABnYXRld2FyZS1hcHAucnBkAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAMDAwMDY0NAAwMDAwMDAwADAwMDAwMDAAMDAwMDAwMDAwNjcAMDAw"
    "MDAwMDAwMDAAMDExMDM0ACAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAHVzdGFyADAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAEZQR0EgYXBwbGljYXRpb24gZ2F0ZXdhcmUgcGF5bG9hZCwg"
    "Zm9yIHRoZSB0ZXN0cyBvbmx5LgoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAA";
// clang-format on

// What GNU tar's default blocking factor pads the file out to.
inline constexpr size_t kStockTarBundleRecordBytes = 10240;

// Decode the fixture and append `padding_bytes` of zeros — the end-of-archive
// blocks.
//
// A base64 decoder of its own, rather than the engine's: the engine's is an
// implementation detail of the signature reader, and a fixture that decoded
// itself with the code under test would be a fixture that agreed with a bug.
inline std::vector<uint8_t> StockTarBundle(size_t padding_bytes) {
  static constexpr std::string_view kAlphabet =
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

  std::vector<uint8_t> bytes;
  uint32_t accumulator = 0;
  int bits = 0;
  for (char character : kStockTarBundleBase64) {
    const size_t symbol = kAlphabet.find(character);
    if (symbol == std::string_view::npos) {
      continue;
    }
    accumulator = (accumulator << 6) | static_cast<uint32_t>(symbol);
    bits += 6;
    if (bits >= 8) {
      bits -= 8;
      bytes.push_back(static_cast<uint8_t>((accumulator >> bits) & 0xFF));
    }
  }

  bytes.resize(bytes.size() + padding_bytes, 0);
  return bytes;
}

}  // namespace ddd::capture::test
