/************************************************************************

    svf_player.h

    Playing a Serial Vector Format programming file through a JTAG cable
    Domesday Duplicator - LaserDisc RF sampler
    SPDX-FileCopyrightText: 2026 Simon Inns
    SPDX-License-Identifier: GPL-3.0-or-later

************************************************************************/

#pragma once

#include <cstddef>
#include <cstdint>
#include <functional>
#include <string>
#include <string_view>

namespace ddd::capture {

class IJtagCable;
class ILogger;

// The whole of this project's FPGA programming knowledge, and the reason
// there is so little of it here.
//
// A Serial Vector Format file is a text description of a JTAG session: which
// instruction registers to load, which data to shift, what to expect back,
// and how long to wait. Quartus writes one from the same chain description
// its own programmer uses, so everything device-specific — how a Cyclone IV
// is configured, how Altera's serial flash loader reaches an EPCS64, which
// bit of which register means "erased" — is decided at build time by the
// tool that already knows it, and lands here as vectors.
//
// What is left is a parser and a TAP state machine, which is a pure function
// from text to a stream of TCK cycles. That is the point: it is tested
// against committed fixtures with no cable and no board, and the only thing
// a bench can add is whether the far end agrees (TESTING.md, B-V1).
//
// The player drives one device on the chain. A file describing a longer
// chain — one with non-empty HIR/HDR/TIR/TDR headers — is refused rather
// than half-understood, because guessing at a chain this project does not
// have would mean shifting a flash image into whatever was actually there.

// The sixteen JTAG TAP states, named as SVF names them.
enum class TapState {
  kReset,
  kIdle,
  kDrSelect,
  kDrCapture,
  kDrShift,
  kDrExit1,
  kDrPause,
  kDrExit2,
  kDrUpdate,
  kIrSelect,
  kIrCapture,
  kIrShift,
  kIrExit1,
  kIrPause,
  kIrExit2,
  kIrUpdate,
};

// The SVF spelling of a state ("RESET", "DRPAUSE"), for messages.
const char* TapStateName(TapState state);

// What a run did, whether or not it finished.
struct SvfPlayResult {
  bool succeeded = false;

  // Set when the caller asked for the run to stop, rather than anything
  // going wrong. The device is then in whatever state the last completed
  // statement left it, which for a flash write means a partly written flash
  // — safe, because the same file can simply be played again, and worth
  // distinguishing from a failure because nothing is wrong with anything.
  bool stopped = false;

  // Written for a user, and empty on success.
  std::string problem;

  // Where in the file it stopped, 1-based, or 0 if nothing was being read.
  size_t line = 0;

  // The keyword of the statement it stopped on ("SDR", "RUNTEST"), or empty
  // if it stopped outside one. Together with the line above this is what
  // turns a report of a failure into something that can be looked up in the
  // file that produced it.
  std::string statement_keyword;

  uint64_t statements = 0;
  uint64_t shifted_bits = 0;
  uint64_t run_clocks = 0;

  // The maximum TCK the file asked for, from its FREQUENCY statement, or 0
  // if it did not name one. Reported rather than obeyed: the USB-Blaster's
  // clock is generated by the cable's own logic and is not the host's to
  // set, so this is something to check a cable against once rather than a
  // knob (see the USB-Blaster documentation page).
  double frequency_hz = 0;
};

// Plays a file through a cable.
//
// One player per run. Nothing here is thread-safe, and every call blocks:
// programming an EPCS64 takes minutes, so this belongs on a worker thread.
class SvfPlayer {
 public:
  // How far through the file the player has read, in bytes. Bytes rather
  // than statements or vectors because it is the one measure that is known
  // before the run starts, so a progress bar built on it is honest from the
  // first update rather than after a guess.
  using ProgressCallback = std::function<void(size_t done, size_t total)>;

  // Returns true to stop the run at the next statement boundary. Asked
  // between statements and never inside one: a scan that has begun is
  // finished, so the cable is never left mid-shift.
  using StopCallback = std::function<bool()>;

  explicit SvfPlayer(IJtagCable& cable, ILogger* logger = nullptr);

  void SetProgressCallback(ProgressCallback callback) {
    progress_ = std::move(callback);
  }
  void SetStopCallback(StopCallback callback) { stop_ = std::move(callback); }

  // Whether there is a device on the far end of the cable.
  //
  // True by default, and set false only to play a file into nothing —
  // which is a real question worth asking ("can this application play this
  // file at all?") and which two things about a real run would answer
  // wrongly. What the file expects on TDO is not compared, because nothing
  // is there to answer and every comparison would fail; and its waits are
  // not held open, because a wait exists for a flash that is not there.
  // Everything else — the parse, the state machine, the vectors, the counts
  // — is exactly what a real run does.
  void SetDeviceAttached(bool attached) { device_attached_ = attached; }

  SvfPlayResult Play(std::string_view text);

 private:
  IJtagCable& cable_;
  ILogger* logger_ = nullptr;
  ProgressCallback progress_;
  StopCallback stop_;
  bool device_attached_ = true;
};

}  // namespace ddd::capture
