#!/usr/bin/env bash
#
# Generate the gateware version stamp.
#
# Domesday Duplicator - LaserDisc RF sampler
# SPDX-FileCopyrightText: 2026 Simon Inns
# SPDX-License-Identifier: GPL-3.0-or-later
#
#   generate-version.sh <output-dir> [commit]
#
# Writes <output-dir>/version.vh, which the top level includes to supply
# spiRegisters with the identity block the FX3 reads back over SPI. The
# register map and the meaning of every bit here are on the "FPGA register
# interface" page of the documentation site.
#
# This is the gateware's counterpart to fx3/firmware/generate-descriptor.sh,
# and deliberately takes the commit the same way: as an argument, falling back
# to asking git only when the caller has not said. A Nix build has no .git to
# consult, and a stamp that silently became "unknown" there would defeat the
# whole point of having one.
#
# The commit is stored as eight ASCII characters rather than as a packed
# number, because it is not always eight characters long: CMake asks git for
# --short=8 while a Nix build passes self.shortRev, which is seven. Text
# represents both without inventing a digit or dropping one, and the host
# compares the two on their common prefix - see
# ddd-gui/src/capture/firmware_version.cpp.

set -euo pipefail

if [ "$#" -lt 1 ]; then
    echo "usage: generate-version.sh <output-dir> [commit]" >&2
    exit 2
fi

output_dir="$1"
commit="${2:-}"

# No commit given, so ask git about the tree this script lives in. Untracked
# files count as dirty: they are not noise, they can be part of the build.
if [ -z "$commit" ]; then
    here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    if commit="$(git -C "$here" rev-parse --short=8 HEAD 2>/dev/null)"; then
        if [ -n "$(git -C "$here" status --porcelain 2>/dev/null)" ]; then
            commit="$commit-dirty"
        fi
    else
        commit="unknown"
    fi
fi

# A dirty build still names the commit it started from. That is the best
# available description of what was compiled; it is simply not the whole of it,
# which is what the flag is for.
bare="${commit%-dirty}"
dirty=0
if [ "$bare" != "$commit" ]; then
    dirty=1
fi

# Anything that is not a hex string is reported as no commit at all rather than
# stored as text, so a reader never has to decide whether the characters it
# received were meant to be a hash. "unknown" is the case this catches.
valid=0
text=""
if [[ "$bare" =~ ^[0-9a-fA-F]{7,40}$ ]]; then
    text="$(printf '%s' "${bare:0:8}" | tr 'A-F' 'a-f')"
    valid=1
else
    dirty=0
fi

# Eight bytes, first character most significant, null padded
hex=""
for (( i = 0; i < 8; i++ )); do
    character="${text:i:1}"
    if [ -n "$character" ]; then
        printf -v byte '%02x' "'$character"
    else
        byte="00"
    fi
    hex="$hex$byte"
done

flags=$(( dirty | (valid << 1) ))

mkdir -p "$output_dir"

cat > "$output_dir/version.vh" <<EOF
/************************************************************************

    version.vh

    Gateware version stamp
    Domesday Duplicator - LaserDisc RF sampler
    SPDX-FileCopyrightText: 2026 Simon Inns
    SPDX-License-Identifier: GPL-3.0-or-later

    Generated by fpga/generate-version.sh - do not edit.

    Commit: $commit

************************************************************************/

\`ifndef GATEWARE_VERSION_VH
\`define GATEWARE_VERSION_VH

\`define GATEWARE_COMMIT_TEXT 64'h$hex
\`define GATEWARE_BUILD_FLAGS 8'h$(printf '%02x' "$flags")

\`endif
EOF
