#!/usr/bin/env bash
#
# Licence-header presence check (T4).
#
# Domesday Duplicator - LaserDisc RF sampler
# SPDX-FileCopyrightText: 2026 Simon Inns
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Runs from the dev shell and from the Nix check, so both take exactly the same path:
#
#   ./tools/check-licence-headers.sh
#   nix build .#checks.x86_64-linux.licence-headers
#
# What it enforces, and what it deliberately does not:
#
#   Enforced — every project-authored source file carries, in its first 40 lines, both a
#   copyright statement and a licence statement. That is the compliance floor: a file with
#   neither is a file nobody can lawfully redistribute with confidence, which is what D22
#   was about.
#
#   Not enforced — that the licence statement is SPDX rather than the long-form GPL notice.
#   AGENTS.md §5.4 adopts SPDX as the convention and converts files opportunistically as
#   they are touched; failing every long-form file today would force exactly the sweeping
#   rewrite that convention exists to avoid. The remaining count is printed on every run so
#   the conversion stays visible rather than being quietly forgotten.
#
# Vendored and generated files are exempt by name below, each with its reason. There is no
# wildcard escape hatch: a new third-party file has to be added here deliberately, which is
# the point — an exemption nobody had to write is an exemption nobody reviewed.

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(dirname "$here")"
verbose=0

# Usage: check-licence-headers.sh [-v] [root]
# The Nix check passes the store path as `root`; a developer passes nothing.
for arg in "$@"; do
    case "$arg" in
        -v) verbose=1 ;;
        *) root="$arg" ;;
    esac
done

# Source extensions the convention covers. Build definitions (CMakeLists.txt, *.cmake),
# workflow YAML and markdown are out of scope: they are configuration rather than the
# copyrightable work, and the project has never headered them.
extensions=(c h cpp inl v py sh nix S)

# Vendored or tool-generated. Never edit these headers — a refresh from the vendor or a
# regeneration overwrites whatever we put there, so a check that demanded our convention
# on them would fail on the next refresh rather than on a real defect.
exempt=(
    # Vendored Cypress/Infineon FX3 SDK — proprietary, refreshed wholesale from the vendor
    # download. Provenance and the licence position are in fx3/sdk/README.md.
    "fx3/sdk"

    # Quartus megafunction wizard output for dcfifo and altpll, carrying Altera's own
    # copyright and licence terms.
    "fpga/src/IPfifo.v"
    "fpga/src/IPfifo_bb.v"
    "fpga/src/IPpllGenerator.v"
    "fpga/src/IPpllGenerator_bb.v"

    # Cypress SDK support code, compiled into the firmware unmodified.
    "fx3/firmware/src/cyfxtx.c"
    "fx3/firmware/src/cyfx_gcc_startup.S"

    # GPIF II Designer output. Says so itself: "This is a generated file and should not be
    # modified". Which .cydsn revision produced it is recorded in
    # fx3/firmware/gpif/README.md.
    "fx3/firmware/src/domesday-duplicator-gpif.h"

    # generate-descriptor.sh output, committed as golden fixtures for the T2 descriptor
    # test. Regenerated by the script, so a hand-added header would not survive.
    "fx3/firmware/tests/descriptor-0123abcd.h"
    "fx3/firmware/tests/descriptor-unknown.h"

    # QCustomPlot, third-party GPLv3, vendored upstream and updated wholesale.
    "gui/src/DomesdayDuplicator/qcustomplot.cpp"
    "gui/src/DomesdayDuplicator/qcustomplot.h"
)

is_exempt() {
    local path="$1" entry
    for entry in "${exempt[@]}"; do
        [[ "$path" == "$entry" || "$path" == "$entry"/* ]] && return 0
    done
    return 1
}

# Only tracked sources are checked. Locally that means asking git, because a working tree
# usually has a gui/build/ full of moc output and CMake probe files, none of which is ours
# to header. Inside the Nix sandbox there is no git and no .git — but the flake source only
# ever contains tracked files, so walking it gives the same set. Hence two ways in and one
# answer.
list_files() {
    if git -C "$root" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        git -C "$root" ls-files -z | tr '\0' '\n'
        return
    fi

    local find_args=() ext
    for ext in "${extensions[@]}"; do
        find_args+=(-o -name "*.$ext")
    done
    find "$root" -type f \( "${find_args[@]:1}" \) -printf '%P\n'
}

# Does this path carry one of the extensions the convention covers?
in_scope() {
    local ext
    for ext in "${extensions[@]}"; do
        [[ "$1" == *.$ext ]] && return 0
    done
    return 1
}

checked=0
exempted=0
longform=0
failed=0
longform_files=()

while IFS= read -r rel; do
    in_scope "$rel" || continue

    if is_exempt "$rel"; then
        exempted=$((exempted + 1))
        continue
    fi

    checked=$((checked + 1))
    header="$(head -40 "$root/$rel")"

    # A copyright statement: the SPDX tag, or the long-form "Copyright (C) …" line the
    # pre-SPDX files use.
    has_copyright=0
    grep -qE 'SPDX-FileCopyrightText:|[Cc]opyright' <<<"$header" && has_copyright=1

    # A licence statement: the SPDX identifier, or the long-form GPL notice.
    has_licence=0
    has_spdx=0
    if grep -q 'SPDX-License-Identifier:' <<<"$header"; then
        has_licence=1
        has_spdx=1
    elif grep -q 'GNU General Public License' <<<"$header"; then
        has_licence=1
    fi

    if [[ $has_copyright -eq 0 || $has_licence -eq 0 ]]; then
        failed=$((failed + 1))
        if [[ $has_copyright -eq 0 && $has_licence -eq 0 ]]; then
            echo "FAIL $rel — no copyright and no licence statement"
        elif [[ $has_copyright -eq 0 ]]; then
            echo "FAIL $rel — licence statement present, no copyright statement"
        else
            echo "FAIL $rel — copyright statement present, no licence statement"
        fi
    elif [[ $has_spdx -eq 0 ]]; then
        longform=$((longform + 1))
        longform_files+=("$rel")
    fi
done < <(list_files | sort)

if [[ $verbose -eq 1 && $longform -gt 0 ]]; then
    echo
    echo "Long-form GPL notice, not yet converted to SPDX:"
    printf '  %s\n' "${longform_files[@]}"
fi

echo
echo "$checked files checked, $exempted exempt (vendored or generated)"

if [[ $failed -gt 0 ]]; then
    echo
    echo "$failed file(s) without a complete licence header."
    echo "Convention and the header to copy: AGENTS.md §5.4."
    exit 1
fi

if [[ $longform -gt 0 ]]; then
    echo "$longform still carry the long-form GPL notice — convert as you touch them (AGENTS.md §5.4)"
fi

echo "Licence headers OK"
