update=10/06/2018 16:00:45
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=Domesday Duplicator-rescue
LibName2=power
LibName3=device
LibName4=transistors
LibName5=conn
LibName6=linear
LibName7=regul
LibName8=74xx
LibName9=cmos4000
LibName10=adc-dac
LibName11=memory
LibName12=xilinx
LibName13=microcontrollers
LibName14=dsp
LibName15=microchip
LibName16=analog_switches
LibName17=motorola
LibName18=texas
LibName19=intel
LibName20=audio
LibName21=interface
LibName22=digital-audio
LibName23=philips
LibName24=display
LibName25=cypress
LibName26=siliconi
LibName27=opto
LibName28=atmel
LibName29=contrib
LibName30=valves
LibName31=ads825
LibName32=de0-nano_gpio
LibName33=opa690
LibName34=gpifii_j7
LibName35=gpifii_j6
LibName36=bnc_rosenberger
LibName37=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName38=C:/Program Files/KiCad/share/kicad/library/74xx
LibName39=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName40=C:/Program Files/KiCad/share/kicad/library/actel
LibName41=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName42=C:/Program Files/KiCad/share/kicad/library/allegro
LibName43=C:/Program Files/KiCad/share/kicad/library/Altera
LibName44=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName45=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName46=C:/Program Files/KiCad/share/kicad/library/atmel
LibName47=C:/Program Files/KiCad/share/kicad/library/audio
LibName48=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName49=C:/Program Files/KiCad/share/kicad/library/bbd
LibName50=C:/Program Files/KiCad/share/kicad/library/bosch
LibName51=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName52=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName53=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName54=C:/Program Files/KiCad/share/kicad/library/conn
LibName55=C:/Program Files/KiCad/share/kicad/library/contrib
LibName56=C:/Program Files/KiCad/share/kicad/library/cypress
LibName57=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName58=C:/Program Files/KiCad/share/kicad/library/device
LibName59=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName60=C:/Program Files/KiCad/share/kicad/library/diode
LibName61=C:/Program Files/KiCad/share/kicad/library/display
LibName62=C:/Program Files/KiCad/share/kicad/library/dsp
LibName63=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName64=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName65=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName66=C:/Program Files/KiCad/share/kicad/library/gennum
LibName67=C:/Program Files/KiCad/share/kicad/library/graphic
LibName68=C:/Program Files/KiCad/share/kicad/library/graphic_symbols
LibName69=C:/Program Files/KiCad/share/kicad/library/hc11
LibName70=C:/Program Files/KiCad/share/kicad/library/infineon
LibName71=C:/Program Files/KiCad/share/kicad/library/intel
LibName72=C:/Program Files/KiCad/share/kicad/library/interface
LibName73=C:/Program Files/KiCad/share/kicad/library/intersil
LibName74=C:/Program Files/KiCad/share/kicad/library/ir
LibName75=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName76=C:/Program Files/KiCad/share/kicad/library/leds
LibName77=C:/Program Files/KiCad/share/kicad/library/LEM
LibName78=C:/Program Files/KiCad/share/kicad/library/linear
LibName79=C:/Program Files/KiCad/share/kicad/library/logic_programmable
LibName80=C:/Program Files/KiCad/share/kicad/library/logo
LibName81=C:/Program Files/KiCad/share/kicad/library/maxim
LibName82=C:/Program Files/KiCad/share/kicad/library/mechanical
LibName83=C:/Program Files/KiCad/share/kicad/library/memory
LibName84=C:/Program Files/KiCad/share/kicad/library/microchip
LibName85=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName86=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName87=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName88=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName89=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName90=C:/Program Files/KiCad/share/kicad/library/microchip_pic24mcu
LibName91=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName92=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName93=C:/Program Files/KiCad/share/kicad/library/modules
LibName94=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName95=C:/Program Files/KiCad/share/kicad/library/motorola
LibName96=C:/Program Files/KiCad/share/kicad/library/motors
LibName97=C:/Program Files/KiCad/share/kicad/library/msp430
LibName98=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName99=C:/Program Files/KiCad/share/kicad/library/nxp
LibName100=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName101=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName102=C:/Program Files/KiCad/share/kicad/library/opto
LibName103=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName104=C:/Program Files/KiCad/share/kicad/library/philips
LibName105=C:/Program Files/KiCad/share/kicad/library/power
LibName106=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName107=C:/Program Files/KiCad/share/kicad/library/powerint
LibName108=C:/Program Files/KiCad/share/kicad/library/pspice
LibName109=C:/Program Files/KiCad/share/kicad/library/references
LibName110=C:/Program Files/KiCad/share/kicad/library/regul
LibName111=C:/Program Files/KiCad/share/kicad/library/relays
LibName112=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName113=C:/Program Files/KiCad/share/kicad/library/RFSolutions
LibName114=C:/Program Files/KiCad/share/kicad/library/sensors
LibName115=C:/Program Files/KiCad/share/kicad/library/silabs
LibName116=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName117=C:/Program Files/KiCad/share/kicad/library/stm8
LibName118=C:/Program Files/KiCad/share/kicad/library/stm32
LibName119=C:/Program Files/KiCad/share/kicad/library/supertex
LibName120=C:/Program Files/KiCad/share/kicad/library/switches
LibName121=C:/Program Files/KiCad/share/kicad/library/texas
LibName122=C:/Program Files/KiCad/share/kicad/library/transf
LibName123=C:/Program Files/KiCad/share/kicad/library/transistors
LibName124=C:/Program Files/KiCad/share/kicad/library/triac_thyristor
LibName125=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName126=C:/Program Files/KiCad/share/kicad/library/valves
LibName127=C:/Program Files/KiCad/share/kicad/library/video
LibName128=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName129=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName130=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName131=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName132=C:/Program Files/KiCad/share/kicad/library/zetex
LibName133=C:/Program Files/KiCad/share/kicad/library/Zilog
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=PDF/
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=Pcbnew
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
