name: Tests

on:
  push:
    paths:
      - '.github/**'
      - 'Linux-Application/**'
  pull_request:
    paths:
      - '.github/**'
      - 'Linux-Application/**'
  release:

jobs:
  qt5:
    name: Build with Qt 5
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2

    - name: Install dependencies
      timeout-minutes: 10
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends cmake qt5-default libqt5serialport5-dev libusb-1.0-0-dev

    - name: Configure
      timeout-minutes: 5
      run: cd Linux-Application && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_QT_VERSION=5 .

    - name: Build
      timeout-minutes: 15
      run: make -C Linux-Application VERBOSE=1

    - name: Install
      timeout-minutes: 5
      run: make -C Linux-Application DESTDIR=/tmp/staging install

  qt6:
    name: Build with Qt 6
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@v2

    - name: Install dependencies
      timeout-minutes: 10
      run: |
        sudo apt-get update
        # libgl-dev is needed by QtGui, but not listed as a dependency
        sudo apt-get install -y --no-install-recommends cmake libgl-dev qt6-base-dev libqt6serialport6-dev libusb-1.0-0-dev

    - name: Configure
      timeout-minutes: 5
      run: cd Linux-Application && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_QT_VERSION=6 .

    - name: Build
      timeout-minutes: 15
      run: make -C Linux-Application VERBOSE=1

    - name: Install
      timeout-minutes: 5
      run: make -C Linux-Application DESTDIR=/tmp/staging install
